name:  buld and deploy 

on:
 workflow_dispatch:
   inputs:
    environment:
     description: "Target env depolyment"
     required: true
     type: choice
     options:
      - 'cloud'
      - 'on-prem'
jobs:
  depoy: 
    runs-on: ubuntu-latest
    steps: 
     - name: checkout repository
       uses: actions/checkout@v4
jobs:
  call-reusable:
  uses: ./.github/workflows/reusable_workflow.yml 
  with:
   env_types: {{ github.event.inputs.environment }}  
        


