name:  buld and deploy 

on:
 workflow_dispatch:
   inputs:
    environment:
     description: "Target env depolyment"
     required: true
     type: choice
     options:
      - cloud
      - on-prem
     default: "cloud" 

jobs:
  call-reusable:
  uses: ./.github/workflows/reusable_workflow.yml 
  with:
   env_type: ${{ github.event.inputs.environment }}  



