name : This is the reusabe workflow
on: 
 workflow_call:
   inputs:
    env_type:
      required: true
      description: "the environment"
      type: string
   outputs:
    resultout_message:
     description: "the resultant value"
     value: ${{ jobs.build.outputs.message }} 
     

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.msg.outputs.msg }}
    steps:
      - name: Print input
        run: echo "Environment received: ${{ inputs.env_type }}"

      - name: Set message
        id: msg
        run: |
          if [ "${{ inputs.env_type }}" = "cloud" ]; then
            echo "msg=Deployed in cloud" >> "$GITHUB_OUTPUT"
          else
            echo "msg=Deployed on-prem" >> "$GITHUB_OUTPUT"
          fi
     